config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  # get 'home/index'
  root 'home#index'

  get 'home/about'

  post '/' => 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  # Stocks belong to one user
  belongs_to :user
  # Symbol must be present in the field
  validates :symbol, presence: true
  # No white spaces
  validates :symbol, format: { without: /\s/ }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Users have many stocks
  has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def about; end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[show edit update destroy]

  # Check the correct user
  before_action :valid_user, only: %i[edit update destroy]

  # Authenticate for logged in user only
  before_action :authenticate_user!

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all

    @api = StockQuote::Stock.new(api_key: 'pk_258efef5f099409aa33aef9fd3c56cd6')
  end

  # GET /stocks/1 or /stocks/1.json
  def show; end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit; end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Allow only the logged in user to make changes to the items they hold
  def valid_user
    # current_user is a devise helper
    @symbol = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: 'Only the valid user can edit the stock' if @symbol.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stock
    @stock = Stock.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def stock_params
    params.require(:stock).permit(:symbol, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<br/>
<%# Custom error message view for existing devise messages %>
<%# Messages are looped %>
<% flash.each do |name, msg| %>
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        <button class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_footer.html.erb
<footer class="navbar navbar-default navbar-static-bottom">
  <div class="container">
  <p class="navbar-text navbar-left"><center>Created by Sandupa Mohottige</center></p>
  </div>
</footer>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "notSTOCK", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add Stocks", new_stock_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Show Stocks", stocks_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>

      <li class="nav-item">
        <%= link_to "About", home_about_path, class: "nav-link" %>
      </li>

    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<div class="jumbotron">
    <h1 class="display-4">About Us</h1>
    <p class="lead">Give what the people want!</p>
    <hr class="my-4">
    <p>The goal of this project is to provide users who are interested in keeping tabs on the stock market a simple and easy way to manage stocks.</p>
    <p>The future for this project will integrate the ability to make stock purchases from the site at reasonable fees.</p>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello, travellers!</h1>
  <p class="lead">Welcome to notSTOCK, a place to find, save and delete (if you really want to) any number of stock options available on the market.</p>
  <hr class="my-4">
  <p>To get started please make an account or sign into an exisiting account.</p>
  <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>notSTOCK</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'home/navbar' %>

    <div class="container">

    <%= render 'home/flash' %>

      <br/>
      <%= yield %>
    </div>

    <%= render 'home/footer' %>

  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Enter <%= form.label :symbol %>
    <%= form.text_field :symbol, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <br/>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<div class="card">
    <div class="card-header">
        <h1>Edit Stock Entry</h1>
    </div>

    <div class="card-body">
        <%= render 'form', stock: @stock %>

        <br/>

        <%= link_to 'Show', @stock, class: 'btn btn-success' %>
        <%= link_to 'Back', stocks_path, class: 'btn btn-secondary' %>
    </div>
</div>

app/views/stocks/index.html.erb
<h1>Stocks</h1>

<table class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Company</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
    <%# Filter stock saved by the logged in user %>
      <% if stock.user_id == current_user.id %>

        <%# Pass user input into stocks api and store results %>
        <% @symbol = StockQuote::Stock.quote(stock.symbol) %>

        <%# This error handling doesn't work due to bad api response %>
        <% if !@symbol %>
          <tr>
            <td><%= link_to 'Error', stock %></td>
            <td><%= stock.symbol %></td>
            <td>N/A</td>
            <td><%= link_to 'Edit', edit_stock_path(stock), class: 'btn btn-warning' %></td>
            <td><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
          </tr>
        <% else %>
          <tr>
            <td><%= link_to @symbol.company_name, stock %></td>
            <td><%= @symbol.symbol %></td>
            <%# Format numbers to 2 decimal places and seperate with comma %>
            <td>$<%= number_with_precision(@symbol.latest_price, :precision => 2, :delimiter => ',') %></td>
            <td><%= link_to 'Edit', edit_stock_path(stock), class: 'btn btn-warning' %></td>
            <td><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>     

      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path, class: 'btn btn-primary' %>

app/views/stocks/new.html.erb
<div class="card">
    <div class="card-header">
        <h1>Add Stock</h1>
    </div>

    <div class="card-body">
        <%= render 'form', stock: @stock %>

        <br/>
        
        <%= link_to 'Back', stocks_path, class: 'btn btn-secondary' %>
    </div>
</div>

app/views/stocks/show.html.erb
<div class="card">
  <% @symbol = StockQuote::Stock.quote(@stock.symbol) %>

  <%# This error handling doesn't work due to bad api response %>
  <% if !@symbol %>
    The symbol: <%= @logo.url %> <br/> does not exist.
  <% else %> 
    <div class="card-header">
      <strong><%= @symbol.company_name %></strong> <br/>
    </div>
      <div class="card-body">
        <% @logo = StockQuote::Stock.logo(@stock.symbol)%>
        <img src="<%= @logo.url %>"><br/><br/>
        Symbol: <%= @symbol.symbol %> <br/>
        Real-Time Price: <%= @symbol.iex_realtime_price %> <br/> 
        <%# Format numbers to 2 decimal places and seperate with comma %>
        Latest Price: $<%= number_with_precision(@symbol.latest_price, :precision => 2, :delimiter => ',') %> <br/>
        Primary Exchange: <%= @symbol.primary_exchange %> <br/>
        Market Cap: <%= @symbol.market_cap %> <br/> 
      <% end %>

      <br/>

      <%= link_to 'Edit', edit_stock_path(@stock), class: 'btn btn-warning' %>
      <%= link_to 'Back', stocks_path, class: 'btn btn-secondary' %>
  </div>

</div>